import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
type Stats={sucKhoe:number;triTue:number;theLuc:number;danhTieng:number;taiSan:number};
type Log={age:number,text:string};type Choice={text:string,result:string,effect:Partial<Stats>};type Event={title:string,body:string,min:number,max:number,choices:Choice[]};
const events:Event[]=[
{title:'Một món đồ bị đánh rơi',body:'Trên đường về nhà, bạn thấy một chiếc ví nằm bên vệ đường. Không có ai ở gần.',min:7,max:15,choices:[{text:'Tìm cách trả lại người mất',result:'Bạn mất cả buổi nhưng cuối cùng tìm được chủ nhân.',effect:{danhTieng:5}},{text:'Giữ lấy tiền bên trong',result:'Bạn mang bí mật nhỏ ấy về nhà.',effect:{taiSan:8}},{text:'Bỏ qua và đi tiếp',result:'Bạn quyết định chuyện này không liên quan tới mình.',effect:{}}]},
{title:'Một cuộc tranh cãi',body:'Hai người xa lạ xô xát ngay trước mặt bạn. Một người có vẻ yếu thế hơn.',min:13,max:80,choices:[{text:'Can ngăn trực tiếp',result:'Bạn lao vào giữa cuộc xô xát.',effect:{theLuc:-4,danhTieng:4}},{text:'Tìm người giúp đỡ',result:'Bạn chọn cách ít liều lĩnh hơn.',effect:{triTue:2}},{text:'Không can dự',result:'Bạn rời đi trước khi rắc rối kéo mình vào.',effect:{}}]},
{title:'Cơ hội học một điều mới',body:'Một người quen giới thiệu cho bạn một khóa học khó nhưng rất đáng thử.',min:10,max:45,choices:[{text:'Dành thời gian học',result:'Những ngày vất vả giúp đầu óc bạn sắc bén hơn.',effect:{triTue:6,taiSan:-3}},{text:'Tập trung kiếm tiền',result:'Bạn bỏ qua cơ hội và dành thời gian cho công việc.',effect:{taiSan:7}},{text:'Tập luyện cơ thể',result:'Bạn chọn rèn luyện bản thân theo một hướng khác.',effect:{theLuc:6}}]},
{title:'Một lời mời bất ngờ',body:'Một người bạn rủ bạn tham gia một dự án nhỏ. Chưa ai biết nó sẽ đi đến đâu.',min:18,max:65,choices:[{text:'Góp tiền và tham gia',result:'Bạn đặt một phần tài sản vào một tương lai chưa rõ ràng.',effect:{taiSan:-8,triTue:3}},{text:'Chỉ góp sức',result:'Bạn tham gia nhưng giữ cho mình một đường lui.',effect:{danhTieng:3,triTue:2}},{text:'Từ chối',result:'Bạn tiếp tục con đường hiện tại.',effect:{}}]},
{title:'Một năm bình lặng',body:'Không có biến cố lớn. Bạn có thời gian nhìn lại cách mình đang sống.',min:0,max:100,choices:[{text:'Chăm sóc sức khỏe',result:'Bạn sống chậm lại và hồi phục.',effect:{sucKhoe:7}},{text:'Đọc và học hỏi',result:'Bạn tích lũy thêm hiểu biết.',effect:{triTue:4}},{text:'Làm việc nhiều hơn',result:'Bạn đổi thời gian lấy tiền bạc.',effect:{taiSan:6,sucKhoe:-3}}]}
];
function rng(seed:number){let t=seed+0x6D2B79F5;return()=>{t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const names=['An','Minh','Lâm','Khánh','Hạ','Vy','Nam','Phong','Linh','Nguyên'];
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
function fresh(seed=Math.floor(Math.random()*99999999)){const r=rng(seed);return{seed,age:0,name:names[Math.floor(r()*names.length)],stats:{sucKhoe:80+Math.floor(r()*16),triTue:25+Math.floor(r()*31),theLuc:25+Math.floor(r()*31),danhTieng:0,taiSan:10},logs:[{age:0,text:'Bạn cất tiếng khóc chào đời. Một nhân sinh mới bắt đầu.'}] as Log[],turn:0,dead:false,current:events[4]}}
type Game=ReturnType<typeof fresh>;const KEY='nhan-sinh-lo-v01';
function App(){const [g,setG]=useState<Game>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||fresh()}catch{return fresh()}});useEffect(()=>localStorage.setItem(KEY,JSON.stringify(g)),[g]);
const title=useMemo(()=>g.dead?'Một đời đã khép lại':g.age<13?'Tuổi thơ':g.age<20?'Tuổi trẻ':g.age<60?'Trưởng thành':'Hậu vận',[g.age,g.dead]);
function nextEvent(age:number,seed:number,turn:number){const valid=events.filter(e=>age>=e.min&&age<=e.max);const r=rng(seed+turn*9973);return valid[Math.floor(r()*valid.length)]||events[4]}
function choose(c:Choice){if(g.dead)return;const age=g.age+1;const s={...g.stats};for(const[k,v]of Object.entries(c.effect))s[k as keyof Stats]=clamp(s[k as keyof Stats]+(v||0));s.sucKhoe=clamp(s.sucKhoe-(age>55?2:age>30?1:0));const dead=s.sucKhoe<=0||age>=82+(g.seed%17);const logs=[...g.logs,{age:g.age,text:g.current.title+' — '+c.result},...(dead?[{age,text:'Cuộc đời khép lại. Những lựa chọn đã trở thành câu chuyện của riêng bạn.'}]:[])];setG({...g,age,stats:s,logs,turn:g.turn+1,dead,current:nextEvent(age,g.seed,g.turn+1)})}
function newLife(){if(confirm('Bắt đầu một nhân sinh mới? Tiến trình hiện tại sẽ được thay thế.'))setG(fresh())}
return <main><header><div><span className="eyebrow">LIFE ROGUELITE • V0.1</span><h1>Nhân Sinh Lộ</h1><p>Mỗi lựa chọn là một bước chân. Không ai biết con đường sẽ dẫn tới đâu.</p></div><button className="ghost" onClick={newLife}>↻ Tân Sinh</button></header>
<section className="grid"><aside className="card person"><div className="avatar">{g.name[0]}</div><h2>{g.name}</h2><div className="muted">{title} • {g.age} tuổi</div><div className="seed">Mệnh số #{g.seed}</div><div className="stats">{Object.entries(g.stats).map(([k,v])=><div className="stat" key={k}><span>{({sucKhoe:'Sức khỏe',triTue:'Trí tuệ',theLuc:'Thể lực',danhTieng:'Danh tiếng',taiSan:'Tài sản'} as any)[k]}</span><b>{v}</b><i><em style={{width:v+'%'}}/></i></div>)}</div></aside>
<section className="card event">{g.dead?<><span className="chapter">BIÊN NIÊN SỬ SƠ KHAI</span><h2>Nhân sinh đã tận</h2><p>Bạn sống đến {g.age} tuổi. V0.1 chưa phán xét cuộc đời bằng một điểm số — hãy nhìn lại những gì đã xảy ra.</p><button className="choice primary" onClick={newLife}>Tân Sinh một cuộc đời khác</button></>:<><span className="chapter">NĂM {g.age} • {title.toUpperCase()}</span><h2>{g.current.title}</h2><p>{g.current.body}</p><div className="choices">{g.current.choices.map((c,i)=><button className="choice" onClick={()=>choose(c)} key={i}><small>LỰA CHỌN {i+1}</small>{c.text}</button>)}</div><div className="hint">Hậu quả không được tiết lộ trước. Hãy chọn điều bạn thực sự muốn làm.</div></>}</section>
<aside className="card timeline"><h3>Dòng đời</h3><div className="scroll">{[...g.logs].reverse().map((l,i)=><div className="log" key={i}><b>{l.age} tuổi</b><span>{l.text}</span></div>)}</div></aside></section><footer>Prototype V0.1 • Tự động lưu trên thiết bị • Responsive PC & Mobile</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);